---

# This playbook tests the script module on Windows hosts



- name: Run powershell script

  hosts: all 

  gather_facts: false

  tasks:

    - name: Run powershell script

      win_command: powershell.exe -ExecutionPolicy ByPass -File C:/temp/helloworld.ps1
