---

# This playbook tests the script module on Windows hosts



- name: Run powershell script

  hosts: all 

  gather_facts: false

  tasks:

    - name: Run powershell script
    
     expect:
      win_command: powershell.exe -ExecutionPolicy ByPass -File C:/temp/helloworld.ps1
      responses:
      Question:
        - response1
        - response2
        - response3
